# Extension configuration file.
# Visit the "Extension configuration file (extension.toml)" section for more details:
# https://docs.omniverse.nvidia.com/kit/docs/kit-manual/latest/guide/extensions_advanced.html
#

[core]
reloadable = true
order = 0

[package]
version = "0.1.0"
title = "mobility"
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.graph" = {}
"omni.graph.tools" = {}
"omni.kit.uiapp" = {}

# define the Python module that the extension provides
[[python.module]]
name = "mobility"

# define the Python module for tests
[[python.module]]
name = "mobility.tests"

[settings]
exts."mobility".timeout = 5

# disable startup test
[[test]]
name = "startup"
enabled = false

[[test]]
enabled = true
dependencies = [
    "omni.kit.test",
]
